{% set name = "psyclone" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/psyclone-{{ version }}.tar.gz
  sha256: 7b369353942358afcb93b199ef2b11116d756cf9d671667ca95fa83fb31f0355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyparsing
    - fparser >=0.2.0
    - configparser
    - jsonschema
    - sympy
    - jinja2
    - termcolor
    - python-graphviz

test:
  imports:
    - psyclone
  commands:
    - pip check
    - psyclone --version  # [not win] CLI not available on Windows
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/stfc/psyclone
  summary: PSyclone - a compiler for Finite Element/Volume/Difference DSLs in Fortran
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ScottWales
